# Generated by Django 3.2.20 on 2023-08-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.PositiveIntegerField(default=5)),
                ('posx', models.IntegerField(default=0)),
                ('posy', models.IntegerField(default=0)),
                ('yspeed', models.IntegerField(default=0)),
                ('xspeed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveIntegerField(default=50)),
                ('posx', models.IntegerField(default=0)),
                ('posy', models.IntegerField(default=0)),
                ('yspeed', models.IntegerField(default=0)),
                ('xspeed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sprite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.PositiveIntegerField(default=100)),
                ('posx', models.IntegerField(default=0)),
                ('posy', models.IntegerField(default=0)),
                ('yspeed', models.IntegerField(default=0)),
                ('xspeed', models.IntegerField(default=0)),
            ],
        ),
    ]
